# Generated by Django 5.2.5 on 2025-11-29 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="Nome da Conta")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CASH", "Dinheiro Físico"),
                            ("CHECKING", "Conta Corrente"),
                            ("SAVINGS", "Poupança"),
                            ("INVESTMENT", "Investimento"),
                            ("CREDIT_CARD", "Cartão de Crédito"),
                        ],
                        default="CHECKING",
                        max_length=20,
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Saldo Inicial",
                    ),
                ),
                (
                    "closing_day",
                    models.PositiveSmallIntegerField(verbose_name="Dia Fechamento"),
                ),
                (
                    "due_day",
                    models.PositiveSmallIntegerField(verbose_name="Dia Vencimento"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta/Carteira",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Slug do ícone (ex: 'mdi-home')",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#000000", help_text="HEX Color", max_length=7
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("INCOME", "Income"), ("EXPENSE", "Expense")],
                        max_length=7,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "unique_together": {("user", "name", "type")},
            },
        ),
    ]
