# Generated by Django 5.2.5 on 2025-12-10 01:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="Account Name")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CASH", "Dinheiro Físico"),
                            ("CHECKING", "Conta Corrente"),
                            ("SAVINGS", "Poupança"),
                            ("INVESTMENT", "Investimento"),
                            ("CREDIT_CARD", "Cartão de Crédito"),
                        ],
                        default="CHECKING",
                        max_length=20,
                        verbose_name="Account Type",
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Initial Balance",
                    ),
                ),
                (
                    "closing_day",
                    models.PositiveSmallIntegerField(verbose_name="Closing Day"),
                ),
                ("due_day", models.PositiveSmallIntegerField(verbose_name="Due Day")),
            ],
            options={
                "verbose_name": "Account",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="Category Name")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Slug of the icon (ex: 'mdi-home')",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#000000",
                        help_text="HEX Color",
                        max_length=7,
                        verbose_name="Color",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("INCOME", "Income"), ("EXPENSE", "Expense")],
                        max_length=7,
                        verbose_name="Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Value"
                    ),
                ),
                ("date", models.DateField(verbose_name="Competence Date")),
                ("paid", models.BooleanField(default=True, verbose_name="Paid")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INCOME", "Income"),
                            ("EXPENSE", "Expense"),
                            ("TRANSFER", "Transfer"),
                        ],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "installment_group_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID that groups installments of the same purchase",
                        null=True,
                        verbose_name="Installment Group ID",
                    ),
                ),
                (
                    "installment_current",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Current installment number (ex: 1)",
                        null=True,
                        verbose_name="Installment Current",
                    ),
                ),
                (
                    "installment_total",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total installments (ex: 12)",
                        null=True,
                        verbose_name="Installment Total",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
