# Generated by Django 5.2.5 on 2025-11-29 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField(verbose_name="Data da Competência")),
                ("paid", models.BooleanField(default=True, verbose_name="Efetivado")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INCOME", "Receita"),
                            ("EXPENSE", "Despesa"),
                            ("TRANSFER", "Transferência"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "installment_group_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID que agrupa parcelas da mesma compra",
                        null=True,
                    ),
                ),
                (
                    "installment_current",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Número da parcela atual (ex: 1)",
                        null=True,
                    ),
                ),
                (
                    "installment_total",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total de parcelas (ex: 12)", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="transactions.account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="transactions.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="transaction_user_id_8af7f1_idx"
                    ),
                    models.Index(
                        fields=["installment_group_id"],
                        name="transaction_install_00eb96_idx",
                    ),
                ],
            },
        ),
    ]
