# Generated by Django 5.2.5 on 2026-05-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="closing_day",
            field=models.PositiveSmallIntegerField(
                blank=True, default=1, null=True, verbose_name="Closing Day"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="due_day",
            field=models.PositiveSmallIntegerField(
                blank=True, default=1, null=True, verbose_name="Due Day"
            ),
        ),
    ]
