# Generated by Django 5.2.5 on 2026-05-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_alter_account_closing_day_alter_account_due_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("DEBIT", "Debit"),
                    ("CREDIT", "Credit"),
                    ("PIX", "Pix"),
                    ("CASH", "Cash"),
                ],
                default="CASH",
                max_length=10,
                verbose_name="Payment Method",
            ),
        ),
    ]
