# Generated by Django 5.2.5 on 2026-07-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Flag to indicate if this is a recurring expense', verbose_name='Is Recurring'),
        ),
    ]
